_wandb:
    value:
        cli_version: 0.23.1
        e:
            aitvbys3qrdj09f73umloc6f8md5ezle:
                args:
                    - --config
                    - /mnt/dataset1/jaeeun/MVR_vggt/RAE/configs/mvrm/DiTDH-XL_DINOv2-B_Multi.yaml
                    - --results-dir
                    - RAE/ckpts/
                    - --image-size
                    - "256"
                    - --precision
                    - fp32
                    - --wandb
                    - --compile
                codePath: RAE/src/je_mvrm_val.py
                codePathLocal: RAE/src/je_mvrm_val.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "943412031488"
                        used: "879737339904"
                email: inthemode@naver.com
                executable: /home/cvlab20/anaconda3/envs/rae/bin/python
                git:
                    commit: 4b2be5ca26f54a8108f03650584b516074350af1
                    remote: https://github.com/babywhale03/MVR.git
                gpu: NVIDIA RTX 5880 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-2271199b-b044-3db5-76fb-2ab926b1001c
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-ac52e656-4520-d502-be3c-b31725ed8894
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-2d538f34-4b02-b6e2-4e7a-0f104c5e4302
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-3a1563a2-1a6e-5219-51b6-d83efb0aa208
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-80ebd768-2c9b-844c-6fe8-46281b36e6a4
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-8ed00583-9104-8ceb-6e40-06ba44542b68
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-f353b9db-f7ba-f153-771d-9e96ca0ca9cc
                    - architecture: Ada
                      cudaCores: 14080
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 5880 Ada Generation
                      uuid: GPU-fa8338eb-24a0-5126-a4d3-1ceffd8f657a
                host: cvlab20
                memory:
                    total: "540809711616"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
                program: /mnt/dataset1/jaeeun/MVR_vggt/RAE/src/je_mvrm_val.py
                python: CPython 3.10.19
                root: /mnt/dataset1/jaeeun/MVR_vggt
                startedAt: "2026-02-12T19:04:19.626030Z"
                writerId: aitvbys3qrdj09f73umloc6f8md5ezle
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 13
                - 14
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.56.2
            "10":
                - 20
            "12": 0.23.1
            "13": linux-x86_64
ckpt:
    value: null
compile:
    value: true
config:
    value: /mnt/dataset1/jaeeun/MVR_vggt/RAE/configs/mvrm/DiTDH-XL_DINOv2-B_Multi.yaml
global_seed:
    value: null
image_size:
    value: 256
precision:
    value: fp32
results_dir:
    value: RAE/ckpts/
wandb:
    value: true
